/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package U1_03_conoceme;

/**
 *
 * @author smadr
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNombre = new javax.swing.JButton();
        btnEdad = new javax.swing.JButton();
        btnComida = new javax.swing.JButton();
        btnOrigen = new javax.swing.JButton();
        btnColor = new javax.swing.JButton();
        btnPostre = new javax.swing.JButton();
        btnCarrera = new javax.swing.JButton();
        btnPelicula = new javax.swing.JButton();
        btnCurp = new javax.swing.JButton();
        btnControl = new javax.swing.JButton();
        lblSalida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNombre.setText("Nombre");
        btnNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNombreMouseClicked(evt);
            }
        });
        btnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreActionPerformed(evt);
            }
        });

        btnEdad.setText("Edad");
        btnEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEdadMouseClicked(evt);
            }
        });

        btnComida.setText("Comida Fav");
        btnComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComidaMouseClicked(evt);
            }
        });

        btnOrigen.setText("Origen");
        btnOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrigenMouseClicked(evt);
            }
        });

        btnColor.setText("Color Fav");
        btnColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorMouseClicked(evt);
            }
        });

        btnPostre.setText("Postre Fav");
        btnPostre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPostreMouseClicked(evt);
            }
        });
        btnPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostreActionPerformed(evt);
            }
        });

        btnCarrera.setText("Carrera");
        btnCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarreraMouseClicked(evt);
            }
        });

        btnPelicula.setText("Pelicula Fav");
        btnPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeliculaMouseClicked(evt);
            }
        });

        btnCurp.setText("Curp");
        btnCurp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCurpMouseClicked(evt);
            }
        });

        btnControl.setText("No. Control");
        btnControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnControlMouseClicked(evt);
            }
        });

        jLabel1.setText("Respuestas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPostre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCurp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(171, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComida)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrigen)
                    .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPostre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCurp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostreActionPerformed
        // TODO add your handling code here:
        lblSalida.setText("Helado");
    }//GEN-LAST:event_btnPostreActionPerformed

    private void btnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreActionPerformed
        // TODO add your handling code here:
        lblSalida.setText("Carlos Sebastian Madrigal Rodriguez");
    }//GEN-LAST:event_btnNombreActionPerformed

    private void btnNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNombreMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("Carlos Sebastian Madrigal Rodriguez");
    }//GEN-LAST:event_btnNombreMouseClicked

    private void btnEdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdadMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("19 años");
    }//GEN-LAST:event_btnEdadMouseClicked

    private void btnComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComidaMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("Pozole");
    }//GEN-LAST:event_btnComidaMouseClicked

    private void btnOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrigenMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("Morelia Mexico");
    }//GEN-LAST:event_btnOrigenMouseClicked

    private void btnColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("Azul");
    }//GEN-LAST:event_btnColorMouseClicked

    private void btnPostreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPostreMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("Helado");
    }//GEN-LAST:event_btnPostreMouseClicked

    private void btnCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarreraMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("ITIC´s");
    }//GEN-LAST:event_btnCarreraMouseClicked

    private void btnPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeliculaMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("Interstellar");
    }//GEN-LAST:event_btnPeliculaMouseClicked

    private void btnCurpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCurpMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("MARC000614HMDDRA5");
        
    }//GEN-LAST:event_btnCurpMouseClicked

    private void btnControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnControlMouseClicked
        // TODO add your handling code here:
        lblSalida.setText("18121699");
    }//GEN-LAST:event_btnControlMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrera;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnComida;
    private javax.swing.JButton btnControl;
    private javax.swing.JButton btnCurp;
    private javax.swing.JButton btnEdad;
    private javax.swing.JButton btnNombre;
    private javax.swing.JButton btnOrigen;
    private javax.swing.JButton btnPelicula;
    private javax.swing.JButton btnPostre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSalida;
    // End of variables declaration//GEN-END:variables
}
