/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package u1_05_capital;

import java.awt.Color;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.chrono.ChronoLocalDate;
import java.time.chrono.ChronoPeriod;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import static java.time.temporal.ChronoUnit.DAYS;
import static java.time.temporal.ChronoUnit.MONTHS;
import static java.time.temporal.ChronoUnit.YEARS;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author smadr
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        btnCalcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taResultado = new javax.swing.JTextArea();
        ffCapital = new javax.swing.JFormattedTextField();
        ffTasa = new javax.swing.JFormattedTextField();
        ffInicio = new javax.swing.JFormattedTextField();
        ffFinal = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Capital");

        jLabel2.setText("Tasa anual");

        jLabel3.setText("Fecha Inico");

        jLabel4.setText("Fecha Final");

        taDescripcion.setColumns(20);
        taDescripcion.setLineWrap(true);
        taDescripcion.setRows(5);
        jScrollPane1.setViewportView(taDescripcion);

        btnCalcular.setText("Calcular");
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });

        taResultado.setColumns(20);
        taResultado.setLineWrap(true);
        taResultado.setRows(5);
        jScrollPane2.setViewportView(taResultado);

        ffCapital.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        ffCapital.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ffCapital.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ffCapitalMouseMoved(evt);
            }
        });
        ffCapital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ffCapitalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ffCapitalMouseExited(evt);
            }
        });

        ffTasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        ffTasa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ffTasa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ffTasaMouseMoved(evt);
            }
        });
        ffTasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ffTasaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ffTasaMouseExited(evt);
            }
        });

        ffInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ffInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ffInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ffInicioMouseMoved(evt);
            }
        });
        ffInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ffInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ffInicioMouseExited(evt);
            }
        });

        ffFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ffFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ffFinal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ffFinalMouseMoved(evt);
            }
        });
        ffFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ffFinalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ffFinalMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ffFinal)
                            .addComponent(ffCapital, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ffTasa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ffInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ffCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ffTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ffInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ffFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
        // TODO add your handling code here:
        double capital = Double.parseDouble(ffCapital.getText());
        double tasa = Double.parseDouble(ffTasa.getText());
        String f1 = ffCapital.getText();
        String f2 = ffTasa.getText();
        taResultado.setText("\nCapital= " + f1 + "\nTasa= " + f2);
        Date fecha1 = null;
        Date fecha2 = null;
        try {
            fecha1 = new SimpleDateFormat("dd/MM/yyyy").parse(f1);
            fecha2 = new SimpleDateFormat("dd/MM/yyyy").parse(f2);
        } catch (ParseException ex){
            //Logger.getLogger(Ventana.class.getName()).log(Level.WARNING, null, ex);
            taDescripcion.setText("Error!");
        }
        double dias =(fecha2.getTime() - fecha1.getTime()) / (24*60*60*1000.0);
        taResultado.append("Dias" + dias +"\n");
        
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        ChronoLocalDate desde = ChronoLocalDate.from(formato.parse(f1));
        ChronoLocalDate hasta = ChronoLocalDate.from(formato.parse(f2));
        ChronoPeriod period = ChronoPeriod.between(desde, hasta);
        taResultado.append("\nAños" + period.get(YEARS) + "\nMeses" + period.get(MONTHS) + "\nDias" + period.get(DAYS));
    }//GEN-LAST:event_btnCalcularMouseClicked

    private void ffCapitalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffCapitalMouseMoved
        // TODO add your handling code here:
        taDescripcion.setText("Es el monto inicial que recibe"
                              + " la persona que solicita el prestamo"
                              + " y es el que se toma como base para el calculo del interes.");
    }//GEN-LAST:event_ffCapitalMouseMoved

    private void ffCapitalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffCapitalMouseEntered
        // TODO add your handling code here:
        ffCapital.setBackground(Color.yellow);
    }//GEN-LAST:event_ffCapitalMouseEntered

    private void ffCapitalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffCapitalMouseExited
        // TODO add your handling code here:
        ffCapital.setBackground(Color.white);
    }//GEN-LAST:event_ffCapitalMouseExited

    private void ffTasaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffTasaMouseEntered
        // TODO add your handling code here:
        ffTasa.setBackground(Color.yellow);
    }//GEN-LAST:event_ffTasaMouseEntered

    private void ffTasaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffTasaMouseExited
        // TODO add your handling code here:
        ffTasa.setBackground(Color.white);
    }//GEN-LAST:event_ffTasaMouseExited

    private void ffInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffInicioMouseEntered
        // TODO add your handling code here:
        ffInicio.setBackground(Color.yellow);
    }//GEN-LAST:event_ffInicioMouseEntered

    private void ffInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffInicioMouseExited
        // TODO add your handling code here:
        ffInicio.setBackground(Color.white);
    }//GEN-LAST:event_ffInicioMouseExited

    private void ffFinalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffFinalMouseEntered
        // TODO add your handling code here:
        ffFinal.setBackground(Color.yellow);
    }//GEN-LAST:event_ffFinalMouseEntered

    private void ffFinalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffFinalMouseExited
        // TODO add your handling code here:
        ffFinal.setBackground(Color.white);
    }//GEN-LAST:event_ffFinalMouseExited

    private void ffTasaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffTasaMouseMoved
        // TODO add your handling code here:
        taDescripcion.setText("La tasa de interés es la cantidad de dinero, "
                + "que por lo regular representa un porcentaje del crédito o "
                + "préstamo que se ha requerido y que el deudor deberá pagar a quien le presta.");
    }//GEN-LAST:event_ffTasaMouseMoved

    private void ffInicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffInicioMouseMoved
        // TODO add your handling code here:
        taDescripcion.setText("Fecha en la que se pidio el prestamo.");
    }//GEN-LAST:event_ffInicioMouseMoved

    private void ffFinalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffFinalMouseMoved
        // TODO add your handling code here:
        taDescripcion.setText("Fecha en la que se conluye el pago del prestamo.");
    }//GEN-LAST:event_ffFinalMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JFormattedTextField ffCapital;
    private javax.swing.JFormattedTextField ffFinal;
    private javax.swing.JFormattedTextField ffInicio;
    private javax.swing.JFormattedTextField ffTasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextArea taResultado;
    // End of variables declaration//GEN-END:variables
}
