package prii_u206_pedidospizza;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

public class ImagenCreditos extends javax.swing.JPanel {
        private ImageIcon icAcercaDe;
    
    public ImagenCreditos(){
        initComponents();
        icAcercaDe = new ImageIcon(getClass().getResource("Pizzeria.PNG"));
    }
    
    public void fijarTamano(Dimension d){
        this.setSize(d);
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Dimension d = this.getSize();
        g.drawImage(icAcercaDe.getImage(), 0, 0, d.width, d.height,null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}