/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package u1_01_holamundo;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author smadr
 */
public class Ventana extends javax.swing.JFrame {
    static Random rand = new Random();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMateria = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        labelCarrera = new javax.swing.JLabel();
        btnDivertido = new javax.swing.JButton();
        labelMateria1 = new javax.swing.JLabel();
        labelMateria2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelMateria.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelMateria.setText("Programacion II");
        labelMateria.setAutoscrolls(true);

        labelNombre1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelNombre1.setText("Carlos Sebastian Madrigal Rodriguez");
        labelNombre1.setAutoscrolls(true);

        labelCarrera.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCarrera.setText("ITIC´s");
        labelCarrera.setAutoscrolls(true);

        btnDivertido.setText("boton Divertido");
        btnDivertido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivertidoActionPerformed(evt);
            }
        });

        labelMateria1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelMateria1.setText("Ramos Diaz J. Guadalupe");
        labelMateria1.setAutoscrolls(true);

        labelMateria2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelMateria2.setText("18121699");
        labelMateria2.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDivertido)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMateria2)
                    .addComponent(labelMateria1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMateria)
                        .addGap(41, 41, 41)
                        .addComponent(labelCarrera)))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(52, Short.MAX_VALUE)
                    .addComponent(labelNombre1)
                    .addGap(30, 30, 30)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMateria)
                    .addComponent(labelCarrera))
                .addGap(18, 18, 18)
                .addComponent(labelMateria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMateria2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnDivertido)
                .addGap(27, 27, 27))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(labelNombre1)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDivertidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivertidoActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < 40; i++) {
        Ventana V = new Ventana();
        int r = rand.nextInt(256);
        int g = rand.nextInt(256);
        int b = rand.nextInt(256);
        V.getContentPane().setBackground(new Color(r,g,b));
       // V.setBackground(c);
        int x = rand.nextInt(1920);
        int y = rand.nextInt(1000);
        V.setLocation(x, y);
        V.setVisible(true);
        }
    }//GEN-LAST:event_btnDivertidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivertido;
    private javax.swing.JLabel labelCarrera;
    private javax.swing.JLabel labelMateria;
    private javax.swing.JLabel labelMateria1;
    private javax.swing.JLabel labelMateria2;
    private javax.swing.JLabel labelNombre1;
    // End of variables declaration//GEN-END:variables
}
